импортировать случайный

класс Танк:
    """Шаблон танков"""

    def __init__(себя, модель, броня, мин_урон, макс_урон, здоровье):
        self.model = модель
        self.armor = броня
        self.damage = random.randint(min_damage, max_damage)
        self.health = здоровье

    защита print_info (сам):
            print(f"{self.model} имеет лобовую броню {self.armor}мм при {self.health}ед. здоровья и урон в {self.damage}единицы")

    def health_down(собственность, враг_урон):
            self.health -= вражеский_урон
            print(f"\n{self.model}:")
            print(f"Командир, по экипажу {self.model} попали, у нас остались очки здоровья {self.health}")


    Def Shot(себя, врага):
            если враг.здоровье <= 0 или себе.урон >= само.здоровье:
                само.здоровье = 0
                print(f"Экипаж танка {enemy.model} уничтожения")
            еще:
                враг.health_down(enemy.damage)
                print(f"\n{self.model}:")
                print(f"Точно в цель, в удалении {enemy.model} осталось {enemy.health}единицы здоровья")

класс SuperTank(Танк):
    """Шаблон супертанка"""
    def __init__(себя, модель, броня, мин_урон, макс_урон, здоровье):
        super().__init__(модель, броня, мин_урон, макс_урон, здоровье)
        self.forceArmor = Истина


    def health_down(собственность, враг_урон):
        super().health_down(enemy_damage / 2)


бак1 = Танк("Т-34", 90, 20, 30, 100)
бак2 = Танк("Тигр", 120, 10, 50, 120)
бак1.print_info()
бак2.print_info()

бак1.выстрел(танк2)
бак1.выстрел(танк2)
бак1.выстрел(танк2)
бак1.выстрел(танк2)
бак1.выстрел(танк2)
бак1.выстрел(танк2)
бак1.выстрел(танк2)
